channels:
     - conda-forge
 dependencies:
     - git
     - dlib
     - numpy
     - scipy
     - opencv
     - face_recognition
     - Pillow
     - transformers
     - torch
     - huggingface_hub
     - pandas
     - python-dotenv
