channels:
     - conda-forge
 dependencies:
     - dlib-bin
     - numpy
     - scipy
     - opencv
     - face_recognition @ git+https://github.com/thetoby9944/face_recognition
     - Pillow
     - transformers
     - torch
     - huggingface_hub
     - pandas
     - python-dotenv
